### ISSUE TITLE
Implement ChaCha20

### ISSUE THREAD

**Issue by cfcs** [abeaumont/ocaml-salsa20-core#3]
Hello!

Would you consider adding support for ChaCha20 as well?

It seems like most new protocols choose ChaCha20 over Salsa20, as recommended by Bernstein in the [ChaCha20 paper](http://cr.yp.to/chacha/chacha-20080128.pdf). I specifically need it for my [WireGuard](https://www.wireguard.com) implementation.

It's my impression that it's a relatively small modification to Salsa20, so I thought it would be a reasonable place to have the code rather than fork the repo and replace it with ChaCha20.

**Comment by cfcs** [comment]
PS: If you don't have time and would rather accept a PR, I'd be happy to do that. :)

**Comment by abeaumont** [comment]
Hi @cfcs!
Note that this repo is rather minimalistic and it only implements Salsa20 Core functions, not even the Salsa20 encryption function (which I've mostly working at https://github.com/abeaumont/ocaml-salsa20). The reason for this is that Salsa20 Core functions are also used outside of Salsa20 encryption function (i.e. https://github.com/abeaumont/ocaml-scrypt-kdf).

Following this reasoning, I think that ChaCha20 deserves its own repo/package. Even if it's only slightly different to Salsa20, its differences are at all levels (quarterrounds, rounds, matrix, etc.), so at the end there's not much code to reuse (and the code is quite simple anyway).

That being said, I also want to see ChaCha20 implemented, so I may just create the new repo and write it. If you're in a rush or want to do it yourself please go ahead and just let me know, and I'll try to contribute as well.

**Comment by cfcs** [comment]
Alright, that makes sense :) I have only done very little OCaml<->C integration, so I think you're much better equipped to do it than I am. I'll need it in 2-3 months from now, so I'll give it a go by then if this pesky "real life" thing has held you up; otherwise I'll just `opam install chacha20` and live happily ever after. I'll ping you if I start writing code :)

**Comment by abeaumont** [comment]
Ok, I've created the repo https://github.com/abeaumont/ocaml-chacha20, you can watch it to keep updated =)
Closing this.
